#!/bin/bash

#swig -c++ -python lib/core/mumoro.i

#python setup.py build_ext --inplace && python server.py scenarios/midi-pyrennees.py
python setup.py build_ext --inplace && python server.py scenarios/toulouse-mixed.py
